// <auto-generated />
namespace Zoe.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CreateSurgery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateSurgery));
        
        string IMigrationMetadata.Id
        {
            get { return "201409152114439_CreateSurgery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
